### ISSUE TITLE
Problem with using `cargo-wasi` in conjunction with `wasm-bindgen`

### ISSUE THREAD

**Issue by nwoods-cimpress** [bytecodealliance/cargo-wasi#110]
I'm having problems using `cargo-wasi` in conjunction with with `wasm-bindgen`.  Specifically, `cargo-wasi` seems to force WebAssembly interface types to be enabled, and if there is a technique to turn it off, I can't seem to find it.

This seems to happen with a completely fresh project.  Steps to reproduce:

1. `cargo new uses-wasm-bindgen --lib`
2. Add `wasm-bindgen = "0.2.78"` to the `[dependencies]` section of `Cargo.toml` 
3. Add `wasm-bindgen-test = "0.3.13"` to the `[dev-dependencies]` section of `Cargo.toml`
4. `cargo wasi test --release`

Running this gives me the following message:

> Error: failed to run main module C:\dev\uses-wasm-bindgen\target\wasm32-wasi\release\deps\uses_wasm_bindgen-40c17809ffa9b77b.wasm
> 
> Caused by:
>     0: failed to parse WebAssembly module
>     1: Unsupported feature: Support for interface types has temporarily been removed from wasmtime.
> 
>        For more information about this temoprary you can read on the issue online:
> 
>            https://github.com/bytecodealliance/wasmtime/issues/1271
> 
>        and for re-adding support for interface types you can see this issue:
> 
>            https://github.com/bytecodealliance/wasmtime/issues/677

Curiously `wasm-pack test --node` works just fine (though it reports no tests to run in this trivial case)

I want to make some use of `wasm-bindgen` to generate bindings so that I can invoke Rust methods from JavaScript, but `cargo-wasi` seems to force on a capability (interface types) not supported by `wasm-bindgen`.  I'm very new to WebAssembly, so I could be making a simple mistake.

**Comment by nwoods-cimpress** [comment]
In my case my entire motivation for using `wasm32-wasi` has been the need to statically link with existing C/C++ code that have dependencies on the standard C/C++ libraries.  None of these libraries was intended to be exposed to `wasm-bindgen` directly; the code between C/C++ and JS was intended to be 100% Rust.

Correct me if I am wrong, but I don't get the standard C/C++ libraries (even `malloc`) if I target `wasm32-unknown-unknown`.

Again I'm new to the ecosystem, but I'd be somewhat surprised if I was the only person trying to do this.  Thanks!

**Comment by nwoods-cimpress** [comment]
So I have one last question, and at this point this is to assuage my intellectual curiosity:

Why would a difference between the `wasm32-unknown-unknown` and `wasm32-wasi` targets manifest themselves as a failure to process the WebAssembler `LocalTee` instruction?  I don't know much about WebAssembler opcodes, but `LocalTee` appears to a WebAssembler opcode, and I would expect the opcodes emitted for all WebAssembler targets to be roughly the same, even if things like calling conventions etc are different.

This feels equivalent to the `clang` x64 backend handling SSE differently for the Linux and Windows platforms.

In any case, thank you so much for your help!

**Comment by teohhanhui** [comment]
Would it make sense to provide a way to disable using `wasm-bindgen` processing even when the `wasm-bindgen` crate is found in the dependencies?
