### ISSUE TITLE
Maybe I found an alternative to cargo-wasi

### ISSUE THREAD

**Issue by tu6ge** [bytecodealliance/cargo-wasi#127]
create `./.cargo/config.toml` file, and write content: 

```
[build]
target = "wasm32-wasi"

[target.wasm32-wasi]
runner = "wasmtime"
```

next, run some cargo command,

- `cargo run`
- `cargo build`
- ...

**Comment by alexcrichton** [comment]
Thanks for the suggestion, and if that works for you I'd encourage you to use it!
