### ISSUE TITLE
Compilation failed ?

### ISSUE THREAD

**Issue by orangeC23** [bytecodealliance/cargo-wasi#136]
## Steps to reproduce
(1) `cargo new testfile`
(2) `cd testfile`
Modify the main.rs :
```

use std::fs::File;
use std::os::unix::io::AsRawFd;

fn main() {
    let file = File::open("./hello.txt").expect("Can not open.");
    let file_descriptor = file.as_raw_fd();
    println!("File descriptor {}", file_descriptor);

}
```

And create file `hello.txt`.

(3) execute `cargo run` , it prints:
```
File descriptor 3
```
(4) However, when execute 'cargo build --target wasm32-wasi', it prints
![image](https://github.com/bytecodealliance/cargo-wasi/assets/28601300/ea2d7594-bf50-4d2a-bf97-b85918a63284)

**Comment by pchickey** [comment]
This issue has to do with Rust `std`, not wasmtime. The `std::os::unix` module is not available when targeting wasi, because wasi is not a unix. There is no equivalent of `AsRawFd` for that target.

What are your needs for `AsRawFd` under wasi?

**Comment by sunfishcode** [comment]
Rust std recently add a new feature, the `std::os::fd` module, which abstracts over `unix` and `wasi`, and contains an [`AsRawFd`](https://doc.rust-lang.org/stable/std/os/fd/trait.AsRawFd.html) which works on both WASI and Unix.

So if you write your program like this:

```rust
use std::fs::File;
use std::os::fd::AsRawFd;

fn main() {
    let file = File::open("./hello.txt").expect("Can not open.");
    let file_descriptor = file.as_raw_fd();
    println!("File descriptor {}", file_descriptor);

}
```

It compiles under both Unix and WASI.

**Comment by orangeC23** [comment]
Thanks a lot ! Now it works !
