### ISSUE TITLE
New release of cargo-wasi that includes the fix for Rust 1.70

### ISSUE THREAD

**Issue by jeffcharles** [bytecodealliance/cargo-wasi#139]
Would it be possible to release a new version of `cargo-wasi` that includes #138?

At the moment, some of our users are complaining that the version of `cargo-wasi` that they're executing after running `$ cargo install cargo-wasi` still has the bug because that version downloads the latest crate release which doesn't include the bugfix.

**Comment by alexcrichton** [comment]
Done now!
