### ISSUE TITLE
Error when building in a workspace

### ISSUE THREAD

**Issue by kyle-mccarthy** [bytecodealliance/cargo-wasi#20]
I am trying to use this inside a workspace to compile one member which will then be called from another member, however it is failing to deserialize the Cargo.toml.

The project structure looks like:

```
Cargo.toml
host
 - Cargo.toml
 - src/main.rs
udf
 - Cargo.toml
 - src/lib.rs
```

The workspace is defined in the top level Cargo.toml, and then I try to call `cargo wasi build` from the udf folder. This errors with the following:

```
< [/code/some_project/udf] cargo wasi build
> Finished dev [unoptimized + debuginfo] target(s) in 0.04s
> error: failed to deserialize as TOML: /code/some_project/Cargo.toml
> Caused by:
>    missing field `package` at line 3 column 1
```

If I add `[package]` to the worspace's Cargo.toml I get the following error:

```
> Caused by:
>   no targets specified in the manifest
>   either src/lib.rs, src/main.rs, a [lib] section, or [[bin]] section must be present
```

**Comment by alexcrichton** [comment]
Oops, should be fixed now, but thanks for the report!
