### ISSUE TITLE
Error when building markdown example

### ISSUE THREAD

**Issue by kubkon** [bytecodealliance/cargo-wasi#24]
While playing with `cargo-wasi`, I've encountered a strange error when trying to build the `markdown` example. Here's the `cargo wasi build` output:

```
kubkon@kubkon-mac ~/d/cargo-wasi> cargo wasi build -p markdown
  Downloaded pulldown-cmark v0.6.1
  Downloaded wasm-bindgen v0.2.50
  Downloaded getopts v0.2.21
  Downloaded memchr v2.2.1
  Downloaded unicase v2.6.0
  Downloaded bitflags v1.2.1
  Downloaded wasm-bindgen-macro v0.2.50
  Downloaded unicode-width v0.1.6
  Downloaded version_check v0.9.1
  Downloaded quote v1.0.2
  Downloaded wasm-bindgen-macro-support v0.2.50
  Downloaded syn v1.0.8
  Downloaded proc-macro2 v1.0.6
  Downloaded wasm-bindgen-shared v0.2.50
  Downloaded wasm-bindgen-backend v0.2.50
  Downloaded unicode-xid v0.2.0
  Downloaded bumpalo v2.6.0
  Downloaded lazy_static v1.4.0
  Downloaded log v0.4.8
   Compiling proc-macro2 v1.0.6
   Compiling unicode-xid v0.2.0
   Compiling log v0.4.8
   Compiling syn v1.0.8
   Compiling wasm-bindgen-shared v0.2.50
   Compiling cfg-if v0.1.10
   Compiling lazy_static v1.4.0
   Compiling version_check v0.9.1
   Compiling bumpalo v2.6.0
   Compiling memchr v2.2.1
   Compiling bitflags v1.2.1
   Compiling wasm-bindgen v0.2.50
   Compiling pulldown-cmark v0.6.1
   Compiling unicode-width v0.1.6
   Compiling unicase v2.6.0
   Compiling getopts v0.2.21
   Compiling quote v1.0.2
   Compiling wasm-bindgen-backend v0.2.50
   Compiling wasm-bindgen-macro-support v0.2.50
   Compiling wasm-bindgen-macro v0.2.50
   Compiling markdown v0.1.0 (/Users/kubkon/dev/cargo-wasi/examples/markdown)
    Finished dev [unoptimized + debuginfo] target(s) in 31.77s
error: failed to generate a standard wasm bindings custom section
    caused by: cannot generate a standalone WebAssembly module which contains an import of wasm-bindgen specific intrinsic `__wbindgen_throw` since it requires JS glue
error: failed to process wasm at `/Users/kubkon/dev/cargo-wasi/target/wasm32-wasi/debug/markdown.rustc.wasm`

Caused by:
    failed to execute "/Users/kubkon/Library/Caches/cargo-wasi/0.1.17/wasm-bindgen/0.2.50/wasm-bindgen" "/Users/kubkon/dev/cargo-wasi/target/wasm32-wasi/debug/markdown.rustc.wasm" "--keep-debug" "--out-dir" "/Users/kubkon/dev/cargo-wasi/target/wasm32-wasi/debug/.tmpdKaBFK" "--out-name" "foo"
        status: exit code: 1
```

To my inexperienced eyes, this looks like a problem with `wasm-bindgen`. In fact, I've traced it down to [this line here].

I'm not sure whether this is the best place to submit the issue since it looks like not a problem with `cargo-wasi` itself, but I thought I'll submit it here first to gather some feedback (looking at you here @alexcrichton ;-) and we'll take it from there.

Oh, and this might be of help, I've tried all `wasm-bindgen` versions starting from `0.2.50` all the way up to `0.2.54`, alas, no joy.

**Comment by alexcrichton** [comment]
Thanks for the report! 

This is a bug with wasm-bindgen right now unfortunately where it requires a release mode build to be compatible with wasm-bindgen. You should be able to build the example with `cargo wasi build --release`.

**Comment by kubkon** [comment]
Ah, tricky! Would you mind if we specified, for the time being, until `wasm-bindgen` bug is fixed, that we added to the README and the book that the users should build in release mode when building with `wasm-bindgen`?

**Comment by kubkon** [comment]
UPDATE: I see you've already added a note to the examples (nice!), but I still feel we should be explicit about this in the book as well, cause I see this as the main point of entry, especially in the beginning. What do you think?

**Comment by alexcrichton** [comment]
Sounds good to me!

I'd also like to leave this open as a reminder to myself to fix this issue, this isn't currently fixed in upstream wasm-bindgen.

**Comment by kubkon** [comment]
Sounds good! Let's leave this open then, to track the issue (that's a great idea indeed!), and in the meantime, I'll submit a PR with the mod to the book (unless you've already done that is).

**Comment by alexcrichton** [comment]
Nah feel free!

**Comment by kubkon** [comment]
> Nah feel free!

Coolios, done now in #26 :-)

**Comment by alexcrichton** [comment]
Ok I've now fixed this in https://github.com/rustwasm/wasm-bindgen/pull/1898. That hasn't landed yet but I'm going to forget to close this when that lands, so I'm going to go ahead and close this. Once that's all deployed and everything settles we can come back and fixup the documentation.
