### ISSUE TITLE
Confusion about table with anyref

### ISSUE THREAD

**Issue by jpopesculian** [bytecodealliance/cargo-wasi#42]
I'm trying to use cargo wasi in conjunction with wasmtime and I'm having difficulties, because I'd like to use the wasm interface types. For example I have a simple rust lib:

```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn add(a: i32, b: i32) -> i32 {
    a + b
}
```

When I compile it with `cargo wasi build --release`, I get the Webassembly module (printed with `wasmprinter`):

```wat
(module
  (type (;0;) (func (param i32 i32) (result i32)))
  (func $add (type 0) (param i32 i32) (result i32)
    local.get 1
    local.get 0
    i32.add)
  (table (;0;) 32 anyref)
  (memory (;0;) 17)
  (global (;0;) (mut i32) (i32.const 1048576))
  (export "memory" (memory 0))
  (export "add" (func $add))
  (data (;0;) (i32.const 1048576) "\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00"))
```
However, the table with anyref generated always seems to throw an error. Specifically with `wasmtime::Config.wasm_reference_types` enabled:

```
thread 'main' panicked at 'not implemented: tables of types other than anyfunc (r64)'
```

I don't know if this is expected behavior, and I'm also confused on why the table is generated in the first place. Any help and explanation would be greatly appreciated

**Comment by jpopesculian** [comment]
Version Information:

```
cargo-wasi 0.1.20 (698008a73d 2020-02-04)
wasm_bindgen 0.2.58
wasmtime / wastime_interface_types 0.9.0 (c9dce98ba21)
```

**Comment by fitzgen** [comment]
Wasmtime doesn't have full `anyref` support yet, notably it is currently missing support for `anyref` tables. These are coming soon tho!

**Comment by alexcrichton** [comment]
Yes it looks like `wasm-bindgen` will unconditionally emit the `anyref` table, even though it doesn't use it. This is arguably a bug though!

Like @fitzgen said though the `wasmtime` crate nor CLI implement the full reference types proposal yet, so that's still very much a work in progress. Until that's implemented the demos with `wasm-bindgen` unfortunately may not work for a bit.

**Comment by alexcrichton** [comment]
In the meantime though I think this is otherwise working as expected, so I'm going to close in favor of https://github.com/bytecodealliance/wasmtime/issues/285

**Comment by alexcrichton** [comment]
I've also opened up https://github.com/rustwasm/wasm-bindgen/issues/1992 to track wasm-bindgen's removal of the table if it's not needed.

**Comment by Drakulix** [comment]
> Version Information:
> 
> ```
> cargo-wasi 0.1.20 (698008a73d 2020-02-04)
> wasm_bindgen 0.2.58
> wasmtime / wastime_interface_types 0.9.0 (c9dce98ba21)
> ```

If you still want to play around with it `wasm-bindgen = "=0.2.54"` seems to generate wasm files that can be loaded by wasmtime.
