### ISSUE TITLE
Failed to run hello world

### ISSUE THREAD

**Issue by stusmall** [bytecodealliance/cargo-wasi#44]
I just tried this project out this morning and hit an issue.  I think I must have missed a step but not sure where.  I can build simple projects but when running them I get an error that "wasi_snapshot_preview1" isn't found.  The wasm file produced runs just fine in a bench build of wasmtime I have.  I have a feeling I missed a step.

Following are versions and output from running

```
$ cargo wasi --version
cargo-wasi 0.1.20 (ad1e122eb2 2020-01-21)
$ rustc --version
rustc 1.41.0 (5e1a79984 2020-01-27)
$ cargo wasi run
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `/home/stusmall/.cargo/bin/cargo-wasi target/wasm32-wasi/debug/wasi-hello-world.wasm`
     Running `target/wasm32-wasi/debug/wasi-hello-world.wasm`
error: failed to process main module `target/wasm32-wasi/debug/wasi-hello-world.wasm`
    caused by: Import module wasi_snapshot_preview1 was not found
```

Please let me know if you need any more information about my host set up

**Comment by alexcrichton** [comment]
Thanks for the report! I think that you probably have an outdated version of `wasmtime` installed, but if you install the latest `wasmtime` from master you should be good to go!

**Comment by stusmall** [comment]
That would do it.  I definitely have an old one, I thought it brought its own.  Thank you very much.,
