### ISSUE TITLE
Execution strategy (lightbeam)

### ISSUE THREAD

**Issue by 0x7CFE** [bytecodealliance/cargo-wasi#48]
Is there a way to somehow pass `--lightbeam` flag to the wasmtime? I could not find a way to do this.

**Comment by alexcrichton** [comment]
Thanks for the report! At this time you unfortunately can't implicitly pass arguments to the runtime, but that's covered by https://github.com/bytecodealliance/cargo-wasi/issues/17 and https://github.com/bytecodealliance/cargo-wasi/pull/19, so I'm going to close in favor of those.
